// packages/react/ui/src/components/primitives/center.tsx
import { cn } from '@/lib/utils'
import type React from 'react'

interface CenterProps {
  children?: React.ReactNode
  inline?: boolean
  class?: string
}

export const Center = (props: CenterProps) => {
  return (
    <div className={cn(props.inline ? 'inline-flex' : 'flex', 'items-center justify-center', props.class)}>
      {props.children}
    </div>
  )
}

// apps/tanstack-solid-app/src/components/ui/center.tsx
import type { JSX } from 'solid-js'
import { cn } from '@/libs/cn'

interface CenterProps {
  children?: JSX.Element
  inline?: boolean
  class?: string
}

export const Center = (props: CenterProps) => {
  return (
    <div class={cn(props.inline ? 'inline-flex' : 'flex', 'items-center justify-center', props.class)}>
      {props.children}
    </div>
  )
}
