// apps/solid-example/src/routes/__root.tsx
import { createRootRouteWithContext, HeadContent, Outlet, Scripts } from "@tanstack/solid-router"
import { TanStackRouterDevtools } from "@tanstack/solid-router-devtools"

import { HydrationScript } from "solid-js/web"
import { Suspense } from "solid-js"

import Header from "../components/Header"

import styleCss from "../styles.css?url"

export const Route = createRootRouteWithContext()({
  head: () => ({
    links: [{ rel: "stylesheet", href: styleCss }],
  }),
  shellComponent: RootComponent,
})

function RootComponent() {
  return (
    <html>
      <head>
        <HydrationScript />
      </head>
      <body>
        <HeadContent />
        <Suspense>
          <Header />

          <Outlet />
          <TanStackRouterDevtools />
        </Suspense>
        <Scripts />
      </body>
    </html>
  )
}

// apps/solid-app/src/routes/__root.tsx
import { Outlet, createRootRouteWithContext } from '@tanstack/solid-router'

import { RuntimeProvider } from '@/services/tanstack-query.js'
import { TanStackRouterDevtools } from '@tanstack/solid-router-devtools'
import Header from '../components/Header.js'

export const Route = createRootRouteWithContext()({
  component: RootComponent,
})

function RootComponent() {
  return (
    <RuntimeProvider>
      <Header />
      <Outlet />
      <TanStackRouterDevtools />
    </RuntimeProvider>
  )
}
