// packages/solid/ui/src/components/primitives/card.tsx
import { cn } from '@effectify/solid-ui/lib/utils'
import type { ComponentProps, ParentComponent } from 'solid-js'
import { splitProps } from 'solid-js'

export const Root = (props: ComponentProps<'div'>) => {
  const [local, rest] = splitProps(props, ['class'])

  return <div class={cn('rounded-xl border bg-card text-card-foreground shadow', local.class)} {...rest} />
}

export const Header = (props: ComponentProps<'div'>) => {
  const [local, rest] = splitProps(props, ['class'])

  return <div class={cn('flex flex-col space-y-1.5 p-6', local.class)} {...rest} />
}

export const Title: ParentComponent<ComponentProps<'h1'>> = (props) => {
  const [local, rest] = splitProps(props, ['class'])

  return <h1 class={cn('font-semibold leading-none tracking-tight', local.class)} {...rest} />
}

export const Description: ParentComponent<ComponentProps<'h3'>> = (props) => {
  const [local, rest] = splitProps(props, ['class'])

  return <h3 class={cn('text-muted-foreground text-sm', local.class)} {...rest} />
}

export const Body = (props: ComponentProps<'div'>) => {
  const [local, rest] = splitProps(props, ['class'])

  return <div class={cn('p-6 pt-0', local.class)} {...rest} />
}

export const Footer = (props: ComponentProps<'div'>) => {
  const [local, rest] = splitProps(props, ['class'])

  return <div class={cn('flex items-center p-6 pt-0', local.class)} {...rest} />
}

// packages/react/ui/src/components/primitives/card.tsx
import { cn } from "@effectify/react-ui/lib/utils"
import type * as React from "react"

function Card({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      className={cn("flex flex-col gap-6 rounded-xl border bg-card py-6 text-card-foreground shadow-sm", className)}
      data-slot="card"
      {...props}
    />
  )
}

function CardHeader({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      className={cn(
        "@container/card-header grid auto-rows-min grid-rows-[auto_auto] items-start gap-1.5 px-6 has-data-[slot=card-action]:grid-cols-[1fr_auto] [.border-b]:pb-6",
        className,
      )}
      data-slot="card-header"
      {...props}
    />
  )
}

function CardTitle({ className, ...props }: React.ComponentProps<"div">) {
  return <div className={cn("font-semibold leading-none", className)} data-slot="card-title" {...props} />
}

function CardDescription({ className, ...props }: React.ComponentProps<"div">) {
  return <div className={cn("text-muted-foreground text-sm", className)} data-slot="card-description" {...props} />
}

function CardAction({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      className={cn("col-start-2 row-span-2 row-start-1 self-start justify-self-end", className)}
      data-slot="card-action"
      {...props}
    />
  )
}

function CardContent({ className, ...props }: React.ComponentProps<"div">) {
  return <div className={cn("px-6", className)} data-slot="card-content" {...props} />
}

function CardFooter({ className, ...props }: React.ComponentProps<"div">) {
  return <div className={cn("flex items-center px-6 [.border-t]:pt-6", className)} data-slot="card-footer" {...props} />
}

export { Card, CardAction, CardContent, CardDescription, CardFooter, CardHeader, CardTitle }
