// apps/solid-example/src/routes/__root.tsx
import { createRootRouteWithContext, HeadContent, Outlet, Scripts } from "@tanstack/solid-router"
import { TanStackRouterDevtools } from "@tanstack/solid-router-devtools"

import { HydrationScript } from "solid-js/web"
import { Suspense } from "solid-js"

import Header from "../components/Header"

import styleCss from "../styles.css?url"

export const Route = createRootRouteWithContext()({
  head: () => ({
    links: [{ rel: "stylesheet", href: styleCss }],
  }),
  shellComponent: RootComponent,
})

function RootComponent() {
  return (
    <html>
      <head>
        <HydrationScript />
      </head>
      <body>
        <HeadContent />
        <Suspense>
          <Header />

          <Outlet />
          <TanStackRouterDevtools />
        </Suspense>
        <Scripts />
      </body>
    </html>
  )
}

// apps/solid-app-spa/src/routes/__root.tsx
import { Outlet, createRootRouteWithContext } from '@tanstack/solid-router'

import { TanStackRouterDevtools } from '@tanstack/solid-router-devtools'
import Header from '../components/Header.js'
import TanStackQueryProvider from '../integrations/tanstack-query/provider.tsx'

export const Route = createRootRouteWithContext()({
  component: RootComponent,
})

function RootComponent() {
  return (
    <>
      <TanStackQueryProvider>
        <Header />

        <Outlet />
        <TanStackRouterDevtools />
      </TanStackQueryProvider>
    </>
  )
}
